spring.application.name=sport_tickets

# ===============================
# CONEXIÓN A MYSQL
# ===============================
# Aquí le decimos a Java dónde está la base de datos (puerto 3306) y cómo se llama (sport_tickets)
spring.datasource.url=jdbc:mysql://localhost:3306/sport_tickets?serverTimezone=UTC
spring.datasource.username=root
# OJO: Si al instalar MySQL le pusiste otra contraseña a 'root', cámbiala aquí
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURACIÓN DE JPA (El traductor)
# ===============================
# "update" hace magia: si creamos una clase en Java, Spring Boot crea la tabla automáticamente en MySQL.
spring.jpa.hibernate.ddl-auto=update
# Esto nos permite ver en la consola los comandos SQL que Spring Boot hace por debajo
spring.jpa.show-sql=true
# Le decimos explícitamente que hable en dialecto MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# CONFIGURACIÓN DE ARCHIVOS (Imágenes)
# ===============================
# Aumentar el límite de tamaño para poder guardar las imágenes en Base64 sin error 500
server.tomcat.max-http-form-post-size=10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB