spring.application.name=sport_tickets
# ===============================
# CONEXIÓN A POSTGRESQL
# ===============================
# Aquí le decimos a Java dónde está la base de datos (puerto 5432) y cómo se llama (sport_ticket_db)
spring.datasource.url=jdbc:postgresql://localhost:5432/sport_ticket_db
spring.datasource.username=postgres
spring.datasource.password=1234

# ===============================
# CONFIGURACIÓN DE JPA (El traductor)
# ===============================
# "update" hace magia: si creamos una clase en Java, Spring Boot crea la tabla automáticamente en Postgres.
spring.jpa.hibernate.ddl-auto=update
# Esto nos permite ver en la consola los comandos SQL que Spring Boot hace por debajo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect